// <auto-generated />
using System;
using Memoriae.DAL.PostgreSQL.EF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Memoriae.DAL.PostgreSQL.EF.Migrations
{
    [DbContext(typeof(PersonalContext))]
    [Migration("20230102114902_TitleCanBeNullMigration")]
    partial class TitleCanBeNullMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasPostgresExtension("pgcrypto")
                .HasAnnotation("Relational:Collation", "Russian_Russia.1251")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AutoSaved")
                        .HasColumnType("boolean");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PreviewText")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Post", "memoriae");
                });

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.PostTagLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagLink", "memoriae");
                });

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Tag", "memoriae");
                });

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.PostTagLink", b =>
                {
                    b.HasOne("Memoriae.DAL.PostgreSQL.EF.Models.Post", "Post")
                        .WithMany("PostTagLink")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Memoriae.DAL.PostgreSQL.EF.Models.Tag", "Tag")
                        .WithMany("PostTagLink")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.Post", b =>
                {
                    b.Navigation("PostTagLink");
                });

            modelBuilder.Entity("Memoriae.DAL.PostgreSQL.EF.Models.Tag", b =>
                {
                    b.Navigation("PostTagLink");
                });
#pragma warning restore 612, 618
        }
    }
}
